### ISSUE TITLE
Update to reflect archival / inactive status

### ISSUE THREAD

**Issue by dheckenberg** [AcademySoftwareFoundation/ci-management#70]
There was discussion at the last CI working group meeting that this repo may be a red herring for people looking to understand / replicate parts of the ASWF CI.

@tykeal would you be able to take a pass mark this repo as archive / inactive?

Thanks
Daniel

**Comment by tykeal** [comment]
@dheckenberg I've closed out all open PRs, locked down options on the repository to limit what can be done here and just changed the description to state it's been archived as of today. You may also notice that I have changed the repo name to be archived-ci-management. That should help folks realize what's what here!
